openapi: 3.0.3
info:
  title: WadLoader3Api
  description: WadLoader3Api
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /wad:
    post:
      description: "Create a new Wad"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/NewWadDto"
      responses:
        201:
          description: "Uploaded new Wad"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadDto'
        400:
          description: "No Wad uploaded"
  /wad/{id}:
    get:
      description: "Get Wad by id"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "The Wad with 'id' id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadDto'
  /wadpack:
    post:
      description: "Create a new WadPack"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewWadPackDto"
      responses:
        201:
          description: "Created new WadPack"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
        400:
          description: "No WadPack created"
  /wadpack/{id}:
    get:
      description: "Get WadPack by id"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "The WadPack with 'id' id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
    delete:
      description: "Delete a WadPack"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: "Deleted WadPack with 'id' id"
        400:
          description: "WadPack not deleted"
    put:
      description: "Update a WadPack"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: "the updated WadPack"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWadPackDto'
      responses:
        200:
          description: "Updated the WadPack"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
components:
  schemas:
    WadDto:
      type: object
      required:
        - id
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: integer
    WadPackDto:
      type: object
      required:
        - name
        - description
        - wads
        - id
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        wads:
          type: array
          items:
            $ref: '#/components/schemas/WadDto'
    NewWadPackDto:
      type: object
      required:
        - name
        - description
        - wads
      properties:
        name:
          type: string
        description:
          type: string
        wads:
          type: array
          items:
            $ref: '#/components/schemas/WadDto'
    NewWadDto:
      type: object
      required:
        - name
        - description
        - file
      properties:
        name:
          type: string
        description:
          type: string
        file:
          type: string
          format: binary