openapi: 3.0.3
info:
  title: WadLoader3Api
  description: WadLoader3Api
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /api/user/new:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserDto"
      responses:
        201:
          description: "A new User was created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        400:
          description: "No User was created"
  /api/hello/{name}:
    get:
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Hello Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloDto'
components:
  schemas:
    NewUserDto:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
    UserDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    HelloDto:
      type: object
      required:
        - name
        - greeting
      properties:
        name:
          type: string
        greeting:
          type: string

