openapi: 3.0.3
info:
  title: WadLoader3Api
  description: WadLoader3Api
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name:
      wadpack
    description:
      api managing wadpacks
  - name:
      wad
    description:
      api managing wads
  - name:
      download
    description:
      api for file downloads
paths:
  /wad:
    post:
      operationId: postWad
      description: "Create a new Wad"
      tags:
        - wad
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/NewWadDto"
      responses:
        200:
          description: "Uploaded new Wad"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadDto'
        400:
          description: "No Wad uploaded"
  /wad/{id}:
    get:
      operationId: getWad
      description: "Get Wad by id"
      tags:
        - wad
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "The Wad with 'id' id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadDto'
  /wadpack:
    post:
      operationId: postWadpack
      description: "Create a new WadPack"
      tags:
        - wadpack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewWadPackDto"
      responses:
        200:
          description: "Created new WadPack"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
        400:
          description: "No WadPack created"
  /wadpack/{id}:
    get:
      operationId: getWadpack
      description: "Get WadPack by id"
      tags:
        - wadpack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "The WadPack with 'id' id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
    delete:
      operationId: deleteWadpack
      description: "Delete a WadPack"
      tags:
        - wadpack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: "Deleted WadPack with 'id' id"
        400:
          description: "WadPack not deleted"
    put:
      operationId: updateWadpack
      description: "Update a WadPack"
      tags:
        - wadpack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: "the updated WadPack"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWadPackDto'
      responses:
        200:
          description: "Updated the WadPack"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WadPackDto'
  /download/handler:
    get:
      operationId: downloadLocalHandler
      tags:
        - download
      description: "download handler to start wads on computer"
      responses:
        200:
          description: "client-handler downloading"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /download/setup:
    get:
      operationId: downloadSetupScript
      tags:
        - download
      description: "download local setup script"
      responses:
        200:
          description: "local setup script download"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /download/wad/{id}:
    get:
      operationId: downloadWad
      tags:
        - download
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/WadIds"
      responses:
        200:
          description: "wad downloading"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: "wad does not exists"
      description: "download the wad with id 'id'"
  /download/wadpack/{id}:
    get:
      operationId: downloadWadpack
      tags:
        - download
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      description: "download all wads of the wadpack and the starting configuration of the wadpack"
      responses:
        200:
          description: "wadpack downloading"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: "wadpack does not exists"
  /download/wadpack/{id}/:
    get:
      operationId: downloadWadPackWithoutWads
      tags:
        - download
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      description: "download no wads of the wadpack and the starting configuration of the wadpack"
      responses:
        200:
          description: "wadpack downloading"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: "wadpack does not exists"
  /download/wadpack/{id}/{ids}:
    get:
      operationId: downloadWadpackWithExplicitWads
      tags:
        - download
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: ids
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/WadIds"
      description: "download all wads of the wadpack and the starting configuration of the wadpack"
      responses:
        200:
          description: "wadpack downloading"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: "wadpack does not exists"
components:
  schemas:
    WadDto:
      type: object
      required:
        - id
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: integer
    WadPackDto:
      type: object
      required:
        - name
        - description
        - wads
        - id
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        wads:
          type: array
          items:
            $ref: '#/components/schemas/WadDto'
    NewWadPackDto:
      type: object
      required:
        - name
        - description
        - wads
      properties:
        name:
          type: string
        description:
          type: string
        wads:
          type: array
          items:
            $ref: '#/components/schemas/WadDto'
    NewWadDto:
      type: object
      required:
        - name
        - description
        - file
      properties:
        name:
          type: string
        description:
          type: string
        file:
          type: string
          format: binary
    WadIds:
      type: array
      items:
        type: integer